// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Vorlesung.Shared.ML.Language
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Language { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string Text { get; set; }
    }
}
